name: sampling_credit
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - tqdm
  - pip
  - pip:
    - vllm
    - torch
    - transformers
    - datasets
    - dynasor
    - accelerate
